# The difference between \ttt{LatticeKrig} and \ttt{LKrig}

As mentioned earlier, \ttt{LKrig} is the function that contains all the logic to compute the kriging fit: it calls the functions to create the covariate matrix, basis function matrix, and precision matrix; runs a series of intermediate calculations; calls another function that calculates the estimates for $\mathbf c$ and $\mathbf d$; uses those coefficients to calculate the fitted values and residuals; calls a function that estimates the likelihood of the calculated fit; and finally estimates the effective degrees of freedom in the fitted surface. While this is a very powerful function, it lacks some ease-of-use features which are provided by \ttt{LatticeKrig}. \ttt{LKrig} has several parameters that need to be set before it can be called; \ttt{LatticeKrig} only needs the data and the locations. \ttt{LatticeKrig} can also automatically filter out any missing data values, but \ttt{LKrig} will fail if provided with missing values. \ttt{LatticeKrig} also makes use of the \ttt{LatticeKrigEasyDefaults} function, which (as the name implies) provides default values for \ttt{NC}, \ttt{nu}, and \ttt{a.wght}. It then builds an \ttt{LKinfo} object, which it uses in a function that estimates \ttt{lambda}, before finally calling \ttt{LKrig} to calculate the kriging fit as described above. 