# Common Errors

## Could not find function

Make sure that the library is installed (\ttt{install.packages("LatticeKrig")}) and loaded (\ttt{library(LatticeKrig)}).

## Need to specify NC for grid size

## Invalid 'times' argument

## Only one alpha specifed for multiple levels

## Missing value where TRUE/FALSE needed

All of these errors can be caused by using \ttt{LKrig} instead of \ttt{LatticeKrig}. The \ttt{LatticeKrig} function has ways to either supply defaults or estimate all of the optional parameters that \ttt{LKrig} doesn't, so \ttt{LKrig} will produce errors like the ones above while \ttt{LatticeKrig} will work correctly. 

## Error in object$x %*% t(Vinv) : non-conformable arguments

This error can occur when using \ttt{LKrigSetup} (or \ttt{LatticeKrig}, by extension) on a 1-dimensional problem if you don't explicitly set \ttt{LKGeometry = "LKInterval"} for \ttt{LKrigSetup}.

## Error in if (ncol(object$x) != 1) { : argument is of length zero

This error most commonly occurs when using \ttt{LKrigSetup} in one dimension and passing in the range of the data explicitly. For example, \ttt{LKrigSetup(c(0,1), ...)} will cause this error (assuming the other arguments are provided correctly). The issue is that the \ttt{c} function doesn't format the input as a matrix, which is the format \ttt{LKrigSetup} expects. To fix this, just call \ttt{as.matrix} on the first parameter you give to \ttt{LKrigSetup} - so we would correct the example above to \ttt{LKrigSetup(as.matrix(c(0,1)), ...)}.